/**
 * Manually written select SQL statements to validate various aspects of the package.
 */
const basicTests = [
  'selec',
  'SELEC',
  'select *',
  'select fo',
  'select * from',
  'select * FROM',
  'SELECT * FROM',
  'select fromm from',
  'select col from table',
  'select col as foo from table',
  'SELECT col FROM table',
  'SELECT col FROM table;',
  'SELECT col FROM table WHERE',
  'SELECT col FROM table where',
  'SELECT foo, bar, baz FROM table;',
  'SELECT MIN(col) FROM table',
  'SELECT min(col) FROM table',
  'SELECT MAX(col) FROM table',
  'SELECT max(col) FROM table',
  'SELECT COUNT(col) FROM table',
  'SELECT count(col) FROM table',
  'SELECT SUM(col) FROM table',
  'SELECT sum(col) FROM table',
  'SELECT AVG(col) FROM table',
  'SELECT avg(col) FROM table',
  'SELECT col1, avg(col) FROM table',
  'SELECT col1, avg(col) as T1 FROM table',
  'SELECT avg(col) as T1 FROM table',
  'SELECT avg(col) as T1, sum(col2) as T2 FROM table',
  'SELECT col FROM table where col',
  'SELECT col FROM table WHERE col',
  'SELECT col FROM table WHERE col =',
  'SELECT col FROM table WHERE col = 1',
  'SELECT col FROM table WHERE col = 1;',
  'SELECT col FROM table WHERE col = true;',
  'SELECT col FROM table WHERE col = TRUE;',
  'SELECT col FROM table WHERE col = false;',
  'SELECT col FROM table WHERE col = FALSE;',
  'SELECT col FROM table WHERE col = null;',
  'SELECT col FROM table WHERE col = NULL;',
  'SELECT col FROM table WHERE col IS null;',
  'SELECT col FROM table WHERE col is NULL;',
  'SELECT col FROM table WHERE col = \'foo\'',
  'SELECT col FROM table WHERE col = "foo"',
  'SELECT col FROM table WHERE col = \'foo\';',
  'SELECT col FROM table WHERE col = "foo";',
  'SELECT col FROM table WHERE col = "foo" and bar > 1',
  'SELECT col FROM table WHERE col = "foo" AND bar > 1',
  'SELECT col FROM table WHERE col = "foo" or bar > 1',
  'SELECT col FROM table WHERE col = "foo" OR bar > 1',
  'SELECT col FROM table WHERE col IN ("foo")',
  'SELECT col FROM table WHERE col IN (\'foo\')',
  'SELECT col FROM table WHERE col in ("foo", "bar")',
  'SELECT col FROM table WHERE col BETWEEN 2 AND 10',
  'SELECT col FROM table WHERE col between 2 and 10',
  'SELECT col FROM table order by',
  'SELECT col FROM table order by col',
  'SELECT col FROM table order by col;',
  'SELECT col FROM table order by col desc',
  'SELECT col FROM table order by col DESC',
  'SELECT col FROM table order by col ASC',
  'SELECT col FROM table order by col asc',
  'SELECT col FROM table limit',
  'SELECT col FROM table limit 5',
  'SELECT col FROM table limit 5;',
  'SELECT col FROM table limit 2, ',
  'SELECT col FROM table limit 2, 5',
  'SELECT col FROM table limit 2, 5;',
  'SELECT distinct col FROM table;',
  'SELECT DISTINCT col FROM table;',
  'SELECT _col FROM table',
  'SELECT _c0O_l FROM table',
  'SELECT col FROM table T1',
  'SELECT column_name\\nFROM table1 T1, table1 T2',
  'SELECT column_name\\nFROM table1 T1,\\ntable1 T2',
  'SELECT column_name\\nFROM table1 T1, table1 T2\\n;',
  'SELECT DISTINCT col FROM table INNER',
  'SELECT DISTINCT col FROM table inner',
  'SELECT DISTINCT col FROM table JOIN',
  'SELECT DISTINCT col FROM table join',
  'SELECT DISTINCT col FROM table INNER JOIN',
  'SELECT DISTINCT col FROM table inner join',
  'SELECT DISTINCT col FROM table LEFT JOIN',
  'SELECT DISTINCT col FROM table left join',
  'SELECT DISTINCT col FROM table RIGHT JOIN',
  'SELECT DISTINCT col FROM table right join',
  'SELECT DISTINCT col FROM table OUTER JOIN',
  'SELECT DISTINCT col FROM table outer join',
  'SELECT DISTINCT col FROM table FULL OUTER JOIN',
  'SELECT DISTINCT col FROM table full outer join',
  'SELECT DISTINCT col FROM table FULL JOIN',
  'SELECT DISTINCT col FROM table full join',
  'SELECT col FROM table union SELECT col FROM table union',
  'SELECT col FROM table UNION SELECT col FROM table UNION select col from table',
  'SELECT col FROM table UNION ALL SELECT col FROM table union all select col from table',
  'SELECT col as col1 FROM t1 JOIN t2 ON t1.id = t2.id',
  'SELECT col as col1 FROM t1 T1 LEFT JOIN t2 T2 ON T1.id = T2.id WHERE T1.id = 1 GROUP BY col1',
  `SELECT teams.conference AS conference,\\nAVG(players.weight) AS average_weight\\n`,
  `SELECT teams.conference AS conference FROM benn.college_football_players players`,
  `SELECT conference FROM p JOIN foo ON foo.school_name = p.school_name`,
  `SELECT conference FROM p JOIN benn.college_football_teams teams\\nON teams.school_name = p.school_name`,
  `SELECT c FROM t ORDER BY AVG(c.f)`,
  `SELECT column1, column2 INTO newtable FROM sourcetable;`,
  `SELECT INTO newtable column1, column2 FROM sourcetable;`,
  `select count(*) from foo join bar on (\n    bar.id = foo.id)`,
  'SELECT count(*) FROM t1 JOIN t2 ON \n  t1.id = t2.id',
];
export default basicTests;
